language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

# command to install dependencies
install: 
  - pip install nose

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq pylint
 
# command to run tests
script: 
  - pylint --rcfile=.pylint.config eagle-library-compare.py
  - nosetests test/
